/**
 * Inline boot polyfills for Chromium <93 (e.g. Android 11 Chrome 91).
 * Must run in a classic <script> before any `type="module"` — ESM / plugin-legacy polyfills load later.
 *
 * - Object.hasOwn, Array/String .at — language APIs
 * - PerformanceEntryList — NOT a global in Chrome 91; patch prototype via performance APIs + PO wrapper
 * - web-vitals LCP: `entries.at(-1)`; some builds also use `_sessionEntries.at`
 */
export const LEGACY_DOM_POLYFILLS_BOOT_SCRIPT = [
  'try{',
  "if(typeof Object.hasOwn!=='function'){",
  'Object.hasOwn=function(o,p){return Object.prototype.hasOwnProperty.call(o,p)}',
  '}',
  'var __aegisAt=function(n){var l=this.length>>0;n=Math.trunc(n)||0;if(n<0)n+=l;return n<0||n>=l?void 0:this[n]};',
  'var __patchAt=function(p){if(p&&!p.at)p.at=__aegisAt};',
  '__patchAt(Array.prototype);',
  '__patchAt(String.prototype);',
  'typeof NodeList!=="undefined"&&__patchAt(NodeList.prototype);',
  'typeof HTMLCollection!=="undefined"&&__patchAt(HTMLCollection.prototype);',
  'typeof DOMTokenList!=="undefined"&&__patchAt(DOMTokenList.prototype);',
  'typeof DOMStringList!=="undefined"&&__patchAt(DOMStringList.prototype);',
  'typeof Int8Array!=="undefined"&&__patchAt(Int8Array.prototype);',
  'typeof Uint8Array!=="undefined"&&__patchAt(Uint8Array.prototype);',
  'typeof Uint8ClampedArray!=="undefined"&&__patchAt(Uint8ClampedArray.prototype);',
  'typeof Int16Array!=="undefined"&&__patchAt(Int16Array.prototype);',
  'typeof Uint16Array!=="undefined"&&__patchAt(Uint16Array.prototype);',
  'typeof Int32Array!=="undefined"&&__patchAt(Int32Array.prototype);',
  'typeof Uint32Array!=="undefined"&&__patchAt(Uint32Array.prototype);',
  'typeof Float32Array!=="undefined"&&__patchAt(Float32Array.prototype);',
  'typeof Float64Array!=="undefined"&&__patchAt(Float64Array.prototype);',
  'typeof BigInt64Array!=="undefined"&&__patchAt(BigInt64Array.prototype);',
  'typeof BigUint64Array!=="undefined"&&__patchAt(BigUint64Array.prototype);',
  'typeof PerformanceEntryList!=="undefined"&&__patchAt(PerformanceEntryList.prototype);',
  'var __patchEntryProto=function(list){',
  'try{if(list&&typeof list.length==="number")__patchAt(Object.getPrototypeOf(list))}catch(e){}',
  '};',
  'var __patchPerfLists=function(){',
  'if(typeof performance==="undefined")return;',
  'var types=["navigation","resource","paint","largest-contentful-paint","layout-shift","longtask","mark","measure","element","event","first-input"];',
  'for(var i=0;i<types.length;i++){',
  'try{var list=performance.getEntriesByType(types[i]);__patchEntryProto(list)}catch(e){}',
  '}',
  'try{__patchEntryProto(performance.getEntries())}catch(e){}',
  '};',
  'if(typeof performance!=="undefined"){',
  'var __nativeGetByType=performance.getEntriesByType&&performance.getEntriesByType.bind(performance);',
  'if(__nativeGetByType){',
  'performance.getEntriesByType=function(type){var list=__nativeGetByType(type);__patchEntryProto(list);return list};',
  '}',
  'var __nativeGetEntries=performance.getEntries&&performance.getEntries.bind(performance);',
  'if(__nativeGetEntries){',
  'performance.getEntries=function(){var list=__nativeGetEntries();__patchEntryProto(list);return list};',
  '}',
  '__patchPerfLists();',
  '}',
  'if(typeof PerformanceObserver!=="undefined"){',
  'var __NativePO=PerformanceObserver;',
  'var __wrapPOCallback=function(cb){return function(list,obs){__patchEntryProto(list&&list.getEntries&&list.getEntries());return cb(list,obs)}};',
  'PerformanceObserver=function(cb){return new __NativePO(__wrapPOCallback(cb))};',
  'PerformanceObserver.prototype=__NativePO.prototype;',
  'if(__NativePO.supportedEntryTypes){',
  'Object.defineProperty(PerformanceObserver,"supportedEntryTypes",{get:function(){return __NativePO.supportedEntryTypes},configurable:true});',
  '}',
  'var __nativeObserve=__NativePO.prototype.observe;',
  'if(__nativeObserve){',
  '__NativePO.prototype.observe=function(opts){var r=__nativeObserve.call(this,opts);__patchPerfLists();return r};',
  '}',
  'try{new __NativePO(function(list){__patchEntryProto(list&&list.getEntries&&list.getEntries())}).observe({type:"paint",buffered:true})}catch(e){}',
  'try{new __NativePO(function(list){__patchEntryProto(list&&list.getEntries&&list.getEntries())}).observe({type:"largest-contentful-paint",buffered:true})}catch(e){}',
  '}',
  '}catch{}',
].join('')
