import { queryKeys } from '~/shared/api/query/query-keys'
import type { DappTab } from '~/shared/config/dapp-tabs'

/** 各 Tab 的查询根前缀——失效与预取共用。 */
export const TAB_QUERY_KEYS: Record<DappTab, readonly (readonly string[])[]> = {
  genesis: [
    queryKeys.api.performance,
    queryKeys.api.salesLogsRoot,
    queryKeys.api.referralTotal,
    queryKeys.api.teamOverview,
    queryKeys.chain.presalePhases,
    queryKeys.chain.presaleAgxPrice,
    queryKeys.chain.presaleTotalPurchased,
    queryKeys.chain.presaleAirdropThreshold,
    queryKeys.chain.presalePaused,
    queryKeys.chain.presaleUserTotal,
    queryKeys.chain.presaleUserPhaseRemainingRoot,
    queryKeys.chain.erc20Root,
    queryKeys.chain.referralRoot,
  ],
  rewards: [
    queryKeys.api.performance,
    queryKeys.api.qualifiedPartitions,
    queryKeys.api.rewardLogsRoot,
    queryKeys.api.referralTotal,
    queryKeys.api.teamRewardTotal,
    queryKeys.api.teamRewardClaimLogsRoot,
    queryKeys.api.communityFundTotal,
    queryKeys.api.communityFundLogsRoot,
    queryKeys.api.teamOverview,
    queryKeys.api.referralAwardSummary,
    queryKeys.api.referralAwardLogsRoot,
    queryKeys.api.referralAwardDirectReferralsRoot,
    queryKeys.api.participationAwardSummary,
    queryKeys.api.participationAwardLogsRoot,
    queryKeys.api.participationAwardInviter,
    queryKeys.api.rankRewardSummary,
    queryKeys.api.rankRewardLogsRoot,
    queryKeys.api.rankRewardPeerSurpassLogsRoot,
    queryKeys.api.rankRewardTeamMembersRoot,
    queryKeys.api.luckyRewardSummary,
    queryKeys.api.luckyRewardMyRoundsRoot,
    queryKeys.api.luckyRewardWinnersRoot,
    queryKeys.api.marketAllowanceSummary,
    queryKeys.api.marketAllowanceClaimLogsRoot,
    queryKeys.api.marketAllowancePaidLogsRoot,
    queryKeys.api.agxContributionSummary,
    queryKeys.api.agxContributionBurnLogsRoot,
    queryKeys.api.agxContributionConsumeLogsRoot,
    queryKeys.chain.rewardsRoot,
    queryKeys.chain.assetsRoot,
    queryKeys.chain.erc20Root,
  ],
  community: [
    queryKeys.api.teamMakingOverview,
    queryKeys.api.teamOverview,
    queryKeys.api.teamReferralsRoot,
    queryKeys.api.performance,
    queryKeys.chain.referralRoot,
  ],
  exchange: [
    queryKeys.chain.swapRoot,
    queryKeys.chain.erc20Root,
    queryKeys.chain.flashSwapRoot,
    queryKeys.chain.burnSwapRoot,
    queryKeys.chain.turbineRoot,
    queryKeys.api.turbineSummary,
    queryKeys.api.turbineLogsRoot,
    queryKeys.api.agxContributionBurnLogsRoot,
    queryKeys.api.agxContributionConsumeLogsRoot,
  ],
  assets: [
    queryKeys.chain.assetsRoot,
    queryKeys.chain.stakingRoot,
    queryKeys.chain.erc20Root,
    queryKeys.chain.burnSwapRoot,
    queryKeys.api.assetsHoldingsSummary,
    queryKeys.api.assetsHoldingsDistribution,
    queryKeys.api.assetsRewardSummary,
    queryKeys.api.assetsProductInvestReward,
    queryKeys.api.stakeFlowLogsRoot,
    queryKeys.api.bondFlowLpLogsRoot,
    queryKeys.api.bondFlowLpRewardTotal,
    queryKeys.api.bondFlowBurnRewardTotal,
    queryKeys.api.bondFlowBurnLogsRoot,
    queryKeys.api.x0MiningLogsRoot,
  ],
  staking: [
    queryKeys.chain.stakingRoot,
    queryKeys.chain.erc20Root,
    queryKeys.chain.referralRoot,
    queryKeys.chain.migrationRoot,
    queryKeys.api.stakeAddressCount,
    queryKeys.api.protocolMarketStatsSeriesRoot,
    queryKeys.api.protocolMarketStatsAggregateRoot,
    queryKeys.api.stakeFlowPositionsRoot,
    queryKeys.api.bondFlowLpPurchasesRoot,
    queryKeys.api.bondFlowBurnPurchasesRoot,
    queryKeys.api.x0MiningPositionsRoot,
  ],
  release: [
    queryKeys.chain.releaseRoot,
    queryKeys.chain.erc20Root,
    queryKeys.chain.turbineRoot,
    queryKeys.api.bufferPoolSummary,
    queryKeys.api.bufferPoolLogsRoot,
    queryKeys.api.releasePoolSummary,
    queryKeys.api.releasePoolLogsRoot,
  ],
}
