export const homeAssets = {
  logoMark: '/assets/figma/home/icons/token-x-mark.webp',
  globe: '/assets/figma/dapp/ic-globe.svg',
  heroVideo: '/assets/figma/home/hero-ip-alpha.webm',
  heroVideoSafari: '/assets/figma/home/hero-ip-alpha.mov',
  heroVideoPoster: '/assets/figma/home/hero-ip-alpha-poster.webp',
  securityCharacter: '/assets/figma/home/security-character-frame@2x.webp',
  securityConnector: '/assets/figma/home/security-connector.svg',
  font: '/assets/fonts/montserrat-latin-variable.woff2',
  protocol: {
    aiThinkTank: '/assets/figma/home/icons/protocol-ai-thinktank.webp',
    usd1: '/assets/figma/home/icons/protocol-usd1.webp',
    globalPayments: '/assets/figma/home/icons/protocol-global-payments.webp',
  },
  engine: {
    marketMaker: '/assets/figma/home/engine-market-maker.webp',
    volatility: '/assets/figma/home/engine-volatility.webp',
    rebase: '/assets/figma/home/engine-rebase.webp',
    turbo: '/assets/figma/home/engine-turbo.webp',
  },
  token: {
    agxIcon: '/assets/figma/home/icons/token-agx-mark.webp',
    agxShape: '/assets/figma/home/icons/token-agx-mark.webp',
    usd1Icon: '/assets/figma/home/icons/token-usd1-icon.svg',
    usd1Shape: '/assets/figma/home/icons/token-usd1-shape.svg',
    xIcon: '/assets/figma/home/icons/token-x-mark.webp',
    xShape: '/assets/figma/home/icons/token-x-mark.webp',
    gagxIcon: '/assets/figma/home/icons/token-gagx-mark.webp',
    gagxShape: '/assets/figma/home/icons/token-gagx-shape.svg',
  },
  partners: {
    usd1: '/assets/figma/home/icons/partner-usd1.svg',
    bsc: '/assets/figma/home/icons/partner-bsc.svg',
    ethereum: '/assets/figma/home/icons/partner-ethereum.svg',
    layerZero: '/assets/figma/home/icons/partner-layerzero.svg',
    chainlink: '/assets/figma/home/icons/partner-chainlink.svg',
    pancakeSwap: '/assets/figma/home/icons/partner-pancakeswap.svg',
  },
  securityCheck: '/assets/figma/home/icons/security-check.svg',
} as const
